spring:
  profiles:
    active: dev
  application:
    name: platform-web

#公共配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.mur.platform.domain
  global-config:
    db-config:
      id-type: uuid
      field-strategy: not_null
  configuration:
    jdbc-type-for-null: null

---
#开发环境
application:
  refreshMenu: true
server:
  port: 8088
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&amp&characterEncoding=utf8
    username: root
    password: root
    tomcat:
      max-active: 100
      validation-interval: 30000
      min-idle: 1
      initial-size: 10
      max-idle: 10
      min-evictable-idle-time-millis: 30000